### ISSUE TITLE
looks like a good idea - preview pics?

### ISSUE THREAD

**Issue by sjb8100** [upscalebaby/Planet#1]
If you have time to drop preview pictures to the repo it would help those passing by know what they might find inside :-)

**Comment by upscalebaby** [comment]
The readme file has some gifs in it, but might be good to post pictures though for sure. I wasn't really planning on posting this project here when I created it, I'll make sure to keep this in mind for upcoming stuff

**Comment by sjb8100** [comment]
I see. I saw those links but didn't realize there were to gifs. The water link is unique to planet stuff, I have not seen that before.

**Comment by upscalebaby** [comment]
Yes I created a hull/domain shader from scratch to learn, should work fine using textures as well though (if i remember correct I did the mesh UVs calculations but never used them in shader). It's very unoptimized and mostly for RND. When looking out on open water from shore you can easily have more than 50% water pixels on screen, all of which are transparent and very expensive. So LODing the water so one mesh is transparent around the viewer, and one for distant ocean that can be opaque is probably a very good starting point
